# Generated by Django 5.0.7 on 2024-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Addminssion_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.PositiveIntegerField(default=0)),
                ('Student_Name', models.CharField(max_length=20)),
                ('mobile', models.PositiveIntegerField(default=0)),
                ('email', models.CharField(default='email', max_length=20)),
                ('Addmission_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
