# Generated by Django 5.0.7 on 2024-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_addminssion_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_addminssion_fee',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
